### ISSUE TITLE
Firefox bugs

### ISSUE THREAD

**Issue by kuusas** [ntacamp/layout#1]
Firefox nerodo LT raidžių, neveikia viršutiniai mygtukai. Tiek ant Ubuntu, tiek ant OSX
https://www.dropbox.com/s/ejglz0pp3v7r4d1/Screenshot%202015-03-27%2010.30.28.png?dl=0

**Comment by Pawka** [comment]
Čia apie master ar develop branch'ą?

**Comment by kuusas** [comment]
Master. Niekas nereagavo, tai galim ignoruot, tuoj bus nauja versija.
